import * as React from 'react'

import Footer from '@/components/base/footer'
import Header from '@/components/base/header'
import { ThemeProvider } from '@/components/base/theme-provider'
import { GoogleAnalytics } from '@next/third-parties/google'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'dw3624 Blog',
  description: 'Generated by create next app',
  icons: {
    icon: '/cookie.svg',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col h-[100dvh]">
            <Header />
            <main className="flex-1 container max-w-3xl">
              <div className="py-6 h-full">{children}</div>
            </main>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
      <GoogleAnalytics gaId="G-Y3D2NTMQYN" />
    </html>
  )
}
